"""empty message

Revision ID: 480f2b0ff7bd
Revises: 17c4e03ba01d
Create Date: 2023-03-27 10:35:54.315475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '480f2b0ff7bd'
down_revision = '17c4e03ba01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['practice_set.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_subjects')
    # ### end Alembic commands ###
